version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rm -f tmp/pids/unicorn.pid && bundle exec unicorn -c config/unicorn.rb"
    volumes:
      - .:/myapp
    ports:
      - "3000"
    depends_on:
      - db
    environment:
      - EDITOR=vim
  
  web:
    image: emarcs/nginx-git
    ports:
      - 80:80
      - "443:443"
    volumes:
      # - /srv/git:/srv/git
      - ./nginx/logs:/var/log/nginx
      # add your custom username and password (default is: admin, admin)
      # - ./htpasswd:/srv/htpasswd
      # if you want to use a custom configuration
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/myapp
    # environment:
      # GIT_POSTBUFFER: 1048576