require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/band_albums", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # BandAlbum. As you add validations to BandAlbum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # BandAlbumsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      BandAlbum.create! valid_attributes
      get band_albums_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      band_album = BandAlbum.create! valid_attributes
      get band_album_url(band_album), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BandAlbum" do
        expect {
          post band_albums_url,
               params: { band_album: valid_attributes }, headers: valid_headers, as: :json
        }.to change(BandAlbum, :count).by(1)
      end

      it "renders a JSON response with the new band_album" do
        post band_albums_url,
             params: { band_album: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BandAlbum" do
        expect {
          post band_albums_url,
               params: { band_album: invalid_attributes }, as: :json
        }.to change(BandAlbum, :count).by(0)
      end

      it "renders a JSON response with errors for the new band_album" do
        post band_albums_url,
             params: { band_album: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested band_album" do
        band_album = BandAlbum.create! valid_attributes
        patch band_album_url(band_album),
              params: { band_album: new_attributes }, headers: valid_headers, as: :json
        band_album.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the band_album" do
        band_album = BandAlbum.create! valid_attributes
        patch band_album_url(band_album),
              params: { band_album: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the band_album" do
        band_album = BandAlbum.create! valid_attributes
        patch band_album_url(band_album),
              params: { band_album: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested band_album" do
      band_album = BandAlbum.create! valid_attributes
      expect {
        delete band_album_url(band_album), headers: valid_headers, as: :json
      }.to change(BandAlbum, :count).by(-1)
    end
  end
end
