require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lyrists", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Lyrist. As you add validations to Lyrist, be sure to
  # adjust the attributes here as well.
  let!(:valid_attributes) {
    artist = create(:artist)
    music = create(:music)
    attributes_for(:lyrist, artist: artist, music: music)
  }

  let(:invalid_attributes) {
    attributes_for(:lyrist, artist: nil)
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # LyristsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Lyrist.create! valid_attributes
      get lyrists_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lyrist = Lyrist.create! valid_attributes
      get lyrist_url(lyrist), as: :json
      expect(response).to be_successful
    end
  end
end
