require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/band_bookmarks', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # BandBookmark. As you add validations to BandBookmark, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # BandBookmarksController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      BandBookmark.create! valid_attributes
      get band_bookmarks_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      band_bookmark = BandBookmark.create! valid_attributes
      get band_bookmark_url(band_bookmark), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new BandBookmark' do
        expect do
          post band_bookmarks_url,
               params: { band_bookmark: valid_attributes }, headers: valid_headers, as: :json
        end.to change(BandBookmark, :count).by(1)
      end

      it 'renders a JSON response with the new band_bookmark' do
        post band_bookmarks_url,
             params: { band_bookmark: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new BandBookmark' do
        expect do
          post band_bookmarks_url,
               params: { band_bookmark: invalid_attributes }, as: :json
        end.to change(BandBookmark, :count).by(0)
      end

      it 'renders a JSON response with errors for the new band_bookmark' do
        post band_bookmarks_url,
             params: { band_bookmark: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested band_bookmark' do
        band_bookmark = BandBookmark.create! valid_attributes
        patch band_bookmark_url(band_bookmark),
              params: { band_bookmark: new_attributes }, headers: valid_headers, as: :json
        band_bookmark.reload
        skip('Add assertions for updated state')
      end

      it 'renders a JSON response with the band_bookmark' do
        band_bookmark = BandBookmark.create! valid_attributes
        patch band_bookmark_url(band_bookmark),
              params: { band_bookmark: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the band_bookmark' do
        band_bookmark = BandBookmark.create! valid_attributes
        patch band_bookmark_url(band_bookmark),
              params: { band_bookmark: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested band_bookmark' do
      band_bookmark = BandBookmark.create! valid_attributes
      expect do
        delete band_bookmark_url(band_bookmark), headers: valid_headers, as: :json
      end.to change(BandBookmark, :count).by(-1)
    end
  end
end
